name: Terraform Dev

on:
  pull_request:
    paths:
      - 'infra/environments/dev/**'

jobs:
  plan:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/924114433913/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'terraform-deployer-dev@lup3-485418.iam.gserviceaccount.com'

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd infra/environments/dev
          terraform init -input=false

      - name: Terraform Validate
        run: |
          cd infra/environments/dev
          terraform validate

      - name: Terraform Plan
        run: |
          cd infra/environments/dev
          terraform plan -no-color

      - name: Run Checkov (IaC Security Scan)
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: infra/
          quiet: true
